### ISSUE TITLE
Unknown Account error message

### ISSUE THREAD

**Issue by CesarAHernandez** [ProjectOpenSea/seaport-js#62] opened 2022-07-01 22:09 UTC
`Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"unknown account\"}}`
Code: 
```
const provider = new ethers.providers.JsonRpcProvider(customUrl, "mainnet");
const seaport = new Seaport(provider);
const { executeAllActions, actions } = await seaport.createOrder(
      {
        offer: [
          {
            itemType: 2,
            token, 
            identifier: tokenId,
            amount: "1",
            endAmount: "1",
          },
        ],
        consideration: [
          {
            itemType: 0,
            identifier: "0",
            amount: "9250000000000000",
            token: "0x0000000000000000000000000000000000000000",
            endAmount: "9250000000000000",
            recipient: offerer,
          },
          {
            itemType: 0,
            identifier: "0",
            token: "0x0000000000000000000000000000000000000000",
            amount: "250000000000000",
            endAmount: "250000000000000",
            recipient: "0x8De9C5A032463C561423387a9648c5C7BCC5BC90",
          },
          {
            itemType: 0,
            identifier: "0",
            token: "0x0000000000000000000000000000000000000000",
            amount: "500000000000000",
            endAmount: "500000000000000",
            recipient: "0x53fa2013286C57114EfF51D6A27E09e46Acc5f89",
          },
        ],
      },
      offerer
    );

    const order = await executeAllActions();
```

I think that issues comes from not having the account private key when creating the message.

Is there a way to provide a signer to seaport that can be used to sign. I have an environment where I cannot expect my users to have Meta Mask installed.

**Comment by sunwrobert** [comment] 2022-07-02 05:16
Yeah this is a duplicate of #52, I think the correct way to handle this is to take in a `signer` in the constructor and use that as the signer if it's provided. If you want to put up a PR for it, feel free. I likely won't be able to get to it until next week.

**Comment by CesarAHernandez** [comment] 2022-07-03 17:09
This solution worked.

**Closed** 2022-07-08 05:21 UTC
